id: P008092
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:01:00.868923
source_metadata:
  id: bdr:W00EGS1017421
  title: ཡང་གསང་རྟ་ཕག་ཡིད་བཞིན་ནོར་བུའི་རྫོགས་ཆེན་ཁྲིད་ཡིག
  author: ''
  volumes:
    c103b97a052249f58295415517df271d:
      image_group_id: I00KG04009
      title: Volume 1 of yang gsang rta phag yid bzhin nor bu'i rdzogs chen khrid
        yig
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
