id: P008092
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017421
  title: ཡང་གསང་རྟ་ཕག་ཡིད་བཞིན་ནོར་བུའི་རྫོགས་ཆེན་ཁྲིད་ཡིག
  author: ''
  volumes:
    406beb6b4d8c4c5a99bc61829fcbd4d2:
      image_group_id: I00KG04009
      title: ''
      volume_number: 1
      total_pages: 442
ebook_metadata:
  title: ཡང་གསང་རྟ་ཕག་ཡིད་བཞིན་ནོར་བུའི་རྫོགས་ཆེན་ཁྲིད་ཡིག
  author: ''
  sku: P008092
  cover: cover.jpg
  layers:
  - pagination
